import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/Header";
import IntroSection from "@/components/IntroSection";
import AnimationProvider from "@/components/modules/AnimationProvider";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700']
})

export const metadata: Metadata = {
  title: 'Caleb Wright',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
      <AnimationProvider>
          <html lang="en">
              <body className={`${inter.className} overflow-x-hidden`}>
                  <IntroSection/>
                  <Header/>
                  {children}
              </body>
          </html>
      </AnimationProvider>

  )
}
